var regiaoSul = [{
			polo:"Florianópolis",
			situacao:"Inscritos" ,
			cor:"#EE82EE",
			address:[{"City":"Antônio Carlos","State":"SC"},
					{"City":"Canelinha","State":"SC"},
					{"City":"Florianópolis","State":"SC"},
					{"City":"Garopaba","State":"SC"},
					{"City":"Palhoça","State":"SC"},
					{"City":"Paulo Lopes","State":"SC"},
					{"City":"São João Batista","State":"SC"},
					{"City":"São José","State":"SC"},
					{"City":"Anita Garibaldi","State":"SC"},
					{"City":"Balneário Camboriú","State":"SC"},
					{"City":"Balneário Gaivota","State":"SC"},
					{"City":"Benedito Novo","State":"SC"},
					{"City":"Biguaçu","State":"SC"},
					{"City":"Blumenau","State":"SC"},
					{"City":"Bom Jesus do Oeste","State":"SC"},
					{"City":"Bombinhas","State":"SC"},
					{"City":"Brusque","State":"SC"},
					{"City":"Camboriú","State":"SC"},
					{"City":"Capivari de Baixo","State":"SC"},
					{"City":"Chapecó","State":"SC"},
					{"City":"Criciúma","State":"SC"},
					{"City":"Dona Emma","State":"SC"},
					{"City":"Içara","State":"SC"},
					{"City":"Imbituba","State":"SC"},
					{"City":"Itajaí","State":"SC"},
					{"City":"Itapema","State":"SC"},
					{"City":"Jaraguá do Sul","State":"SC"},
					{"City":"Joinville","State":"SC"},
					{"City":"Laguna","State":"SC"},
					{"City":"Lauro Muller","State":"SC"},
					{"City":"Luiz Alves","State":"SC"},
					{"City":"Meleiro","State":"SC"},
					{"City":"Mirim Doce","State":"SC"},
					{"City":"Navegantes","State":"SC"},
					{"City":"Nova Erechim","State":"SC"},
					{"City":"Nova Trento","State":"SC"},
					{"City":"Paial","State":"SC"},
					{"City":"Piçarras","State":"SC"},
					{"City":"Presidente Castelo Branco","State":"SC"},
					{"City":"Rio Rufino","State":"SC"},
					{"City":"Salto Veloso","State":"SC"},
					{"City":"Santa Rosa de Lima","State":"SC"},
					{"City":"São Francisco do Sul","State":"SC"},
					{"City":"São Miguel da Boa Vista","State":"SC"},
					{"City":"Sombrio","State":"SC"},
					{"City":"Taió","State":"SC"},
					{"City":"Tangará","State":"SC"},
					{"City":"Tijucas","State":"SC"},
					{"City":"Timbó","State":"SC"},
					{"City":"Tubarão","State":"SC"},
					{"City":"Urubici","State":"SC"},
					{"City":"Urussanga","State":"SC"},
					{"City":"Vargem","State":"SC"},
					{"City":"Vidal Ramos","State":"SC"}]},
				{polo:"Florianópolis",
				situacao:"Concluiram" ,
				cor:"#8A2BE2",
				address:[{"City":"Florianópolis","State":"SC"},
					{"City":"São José","State":"SC"},
					{"City":"Navegantes","State":"SC"},
					{"City":"Capivari de Baixo","State":"SC"},
					{"City":"Palhoça","State":"SC"},
					{"City":"Chapecó","State":"SC"},
					{"City":"Balneário Camboriú","State":"SC"},
					{"City":"Sombrio","State":"SC"},
					{"City":"Anita Garibaldi","State":"SC"},
					{"City":"Dona Emma","State":"SC"},
					{"City":"Garopaba","State":"SC"},
					{"City":"Benedito Novo","State":"SC"},
					{"City":"Presidente Castelo Branco","State":"SC"},
					{"City":"Brusque","State":"SC"},
					{"City":"São João Batista","State":"SC"},
					{"City":"Tubarão","State":"SC"},
					{"City":"Taió","State":"SC"},
					{"City":"Bom Jesus do Oeste","State":"SC"},
					{"City":"Bombinhas","State":"SC"},
					{"City":"Blumenau","State":"SC"},
					{"City":"Meleiro","State":"SC"},
					{"City":"Urubici","State":"SC"},
					{"City":"Urussanga","State":"SC"},
					{"City":"Itajaí","State":"SC"},
					{"City":"Luiz Alves","State":"SC"},
					{"City":"Timbó","State":"SC"},
					{"City":"Tijucas","State":"SC"},
					{"City":"Joinville","State":"SC"},
					{"City":"Laguna","State":"SC"},
					{"City":"Rio Rufino","State":"SC"},
					{"City":"Antônio Carlos","State":"SC"},
					{"City":"Paulo Lopes","State":"SC"},
					{"City":"Canelinha","State":"SC"},
					{"City":"Itapema","State":"SC"},
					{"City":"Santa Rosa de Lima","State":"SC"},
					{"City":"Piçarras","State":"SC"}]},	
				{polo:"Porto Alegre",
				situacao:"Inscritos" ,
				cor:"#87CEFA",
				address:[{"City":"Aceguá","State":"RS"},
					{"City":"Ajuricaba","State":"RS"},
					{"City":"Alegrete","State":"RS"},
					{"City":"Alvorada","State":"RS"},
					{"City":"Arroio do Padre","State":"RS"},
					{"City":"Arvorezinha","State":"RS"},
					{"City":"Benjamin Constant do Sul","State":"RS"},
					{"City":"Cachoeira do Sul","State":"RS"},
					{"City":"Cachoeirinha","State":"RS"},
					{"City":"Camaquã","State":"RS"},
					{"City":"Campo Novo","State":"RS"},
					{"City":"Canoas","State":"RS"},
					{"City":"Capão da Canoa","State":"RS"},
					{"City":"Catuípe","State":"RS"},
					{"City":"Charqueadas","State":"RS"},
					{"City":"Coronel Barros","State":"RS"},
					{"City":"Cruzaltense","State":"RS"},
					{"City":"Eldorado do Sul","State":"RS"},
					{"City":"Ernestina","State":"RS"},
					{"City":"Farroupilha","State":"RS"},
					{"City":"Glorinha","State":"RS"},
					{"City":"Gramado","State":"RS"},
					{"City":"Gravataí","State":"RS"},
					{"City":"Guaíba","State":"RS"},
					{"City":"Guarani das MissÃµes","State":"RS"},
					{"City":"Ijuí","State":"RS"},
					{"City":"Itaqui","State":"RS"},
					{"City":"Itati","State":"RS"},
					{"City":"Jaquirana","State":"RS"},
					{"City":"Marau","State":"RS"},
					{"City":"Minas do Leão","State":"RS"},
					{"City":"Monte Alegre dos Campos","State":"RS"},
					{"City":"Nova Bassano","State":"RS"},
					{"City":"Nova Boa Vista","State":"RS"},
					{"City":"Nova Petrópolis","State":"RS"},
					{"City":"Nova Prata","State":"RS"},
					{"City":"Novo Hamburgo","State":"RS"},
					{"City":"Osório","State":"RS"},
					{"City":"Planalto","State":"RS"},
					{"City":"Porto Alegre","State":"RS"},
					{"City":"Rio Grande","State":"RS"},
					{"City":"Rosário do Sul","State":"RS"},
					{"City":"Santo Ângelo","State":"RS"},
					{"City":"São Domingos do Sul","State":"RS"},
					{"City":"São Leopoldo","State":"RS"},
					{"City":"São Lourenço do Sul","State":"RS"},
					{"City":"São Martinho","State":"RS"},
					{"City":"São Valério do Sul","State":"RS"},
					{"City":"Sapiranga","State":"RS"},
					{"City":"Sapucaia do Sul","State":"RS"},
					{"City":"Silveira Martins","State":"RS"},
					{"City":"Sobradinho","State":"RS"},
					{"City":"Tapes","State":"RS"},
					{"City":"Uruguaiana","State":"RS"},
					{"City":"Vacaria","State":"RS"},
					{"City":"Veranópolis","State":"RS"},
					{"City":"Vista Alegre","State":"RS"},
					{"City":"Vista Gaúcha","State":"RS"},
					{"City":"Xangri-lá","State":"RS"}]},
				{polo:"Porto Alegre",
				situacao:"Concluiram",
				cor:"#00BFFF",
				address:[{"City":"Porto Alegre","State":"RS"},
					 {"City":"Sapucaia do Sul","State":"RS"},
					 {"City":"Itati","State":"RS"},
					 {"City":"Canoas","State":"RS"},
					 {"City":"Planalto","State":"RS"},
					 {"City":"Marau","State":"RS"},
					 {"City":"Vacaria","State":"RS"},
					 {"City":"Rio Grande","State":"RS"},
					 {"City":"Ajuricaba","State":"RS"},
					 {"City":"Charqueadas","State":"RS"},
					 {"City":"Nova Prata","State":"RS"},
					 {"City":"Monte Alegre dos Campos","State":"RS"},
					 {"City":"Santo Ângelo","State":"RS"},
					 {"City":"Rosário do Sul","State":"RS"},
					 {"City":"Nova Bassano","State":"RS"},
					 {"City":"Jaquirana","State":"RS"},
					 {"City":"Alvorada","State":"RS"},
					 {"City":"Catuípe","State":"RS"},
					 {"City":"Cachoeira do Sul","State":"RS"},
					 {"City":"Arvorezinha","State":"RS"},
					 {"City":"Gramado","State":"RS"},
					 {"City":"Benjamin Constant do Sul","State":"RS"},
					 {"City":"Novo Hamburgo","State":"RS"},
					 {"City":"Ijuí","State":"RS"},
					 {"City":"Silveira Martins","State":"RS"},
					 {"City":"Farroupilha","State":"RS"},
					 {"City":"São Leopoldo","State":"RS"},
					 {"City":"Eldorado do Sul","State":"RS"},
					 {"City":"Gravataí","State":"RS"}]}];
